### ISSUE TITLE
Single file download don‘t work

### ISSUE THREAD

**Issue by charles9056** [camsong/chrome-github-mate#40]
the button  'click to download' is disappeared.

**Comment by duianto** [comment]
The Download button is visible when viewing a single file, ex:
https://github.com/camsong/chrome-github-mate/blob/master/README.md

![chrome_2018-09-18_13-48-20](https://user-images.githubusercontent.com/13420573/45685419-91ec7680-bb49-11e8-9205-f03d68ef4ef2.png)


But when the Download button is clicked, then it works the same way as the default Raw button, which opens the file as text:
https://raw.githubusercontent.com/camsong/chrome-github-mate/master/README.md

The file doesn't start downloading as one would expect.

**Comment by camsong** [comment]
This is because the `<a>` `download` attribute does not support cross origin download, according to:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Attributes

> This attribute only works for same-origin URLs.

When you clock 'download' button, GitHub will redirect you to `https://raw.githubusercontent.com/xxx`, will violate the same-origin policy.
Right now, this is no work around ☹

same with https://github.com/camsong/chrome-github-mate/issues/41
